In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("housing_prices_MLR.csv")
dataset.head()

AREA  FLOOR  ROOM CODE  PRICE
0  1000      7     2    B   5618
1  1030      7     1    A   5201
2  1060      1     1    A   4779
3  1090      6     1    A   5425
4  1120      0     2    B   5657

In [3]:
dataset.isnull().values.any()

False

In [4]:
x=dataset.iloc[0:, 0:4]
y=dataset.iloc[0:, 4:]
x=x.values
y=y.values


# instead of OneHot did ColumnTransfer

In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x=LabelEncoder()
x[0:,3]=labelencoder_x.fit_transform(x[0:,3])
ct=ColumnTransformer([('one_hot_encoder', OneHotEncoder('auto'), [3])], remainder='passthrough')
x=np.array(ct.fit_transform(x), dtype=np.float)
x

array([[0.00e+00, 1.00e+00, 1.00e+03, 7.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.03e+03, 7.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.06e+03, 1.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.09e+03, 6.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.12e+03, 0.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.15e+03, 1.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.18e+03, 6.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.21e+03, 0.00e+00, 1.00e+00],
       [0.00e+00, 1.00e+00, 1.24e+03, 0.00e+00, 2.00e+00],
       [1.00e+00, 0.00e+00, 1.27e+03, 7.00e+00, 1.00e+00],
       [1.00e+00, 0.00e+00, 1.30e+03, 1.00e+01, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.33e+03, 3.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.36e+03, 3.00e+00, 3.00e+00],
       [0.00e+00, 1.00e+00, 1.39e+03, 8.00e+00, 3.00e+00],
       [1.00e+00, 0.00e+00, 1.42e+03, 3.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.45e+03, 7.00e+00, 2.00e+00],
       [0.00e+00, 1.00e+00, 1.48e+03, 8.00e+00, 3.00e+00

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [7]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()
model=linear.fit(x_train,y_train)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
prediction=model.predict(x_train)
prediction

array([[ 9688.45160367],
       [ 5796.36525724],
       [15948.76088502],
       [ 9228.84562356],
       [10106.27743223],
       [10524.64650052],
       [13189.89055843],
       [11797.68103626],
       [10183.40064726],
       [10733.69522473],
       [ 8532.19762276],
       [ 4152.51199975],
       [ 7050.38598267],
       [ 9766.66129814],
       [10481.77986954],
       [10892.79917083],
       [16296.81326556],
       [ 8811.56303472],
       [15759.26921085],
       [ 7488.04048113],
       [ 4292.60213552],
       [15600.98012434],
       [12911.34000605],
       [13240.65019613],
       [11151.79267316],
       [ 4063.7247414 ],
       [ 9646.39983227],
       [15600.70850448],
       [ 7417.45217353],
       [ 8183.87362236],
       [10265.65299819],
       [14354.85240565],
       [10543.9319307 ],
       [ 9201.66718666],
       [13190.70541801],
       [ 6562.51508621],
       [14835.10191523],
       [ 6424.05466961],
       [ 3943.46327553],
       [ 7885.49440008]])

In [9]:
input=[[0.0, 1.0, 1000, 7, 2]]
ans=model.predict(input)
ans

array([[5796.36525724]])

In [10]:
r=model.score(x_train,y_train)
r

0.9636736030414367