In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("housing_prices_MLR.csv")
dataset.head()

AREA  FLOOR  ROOM CODE  PRICE
0  1000      7     2    B   5618
1  1030      7     1    A   5201
2  1060      1     1    A   4779
3  1090      6     1    A   5425
4  1120      0     2    B   5657

In [3]:
dataset.isnull().values.any()

False

In [4]:
x=dataset.iloc[0:, 0:4]
y=dataset.iloc[0:, 4:]
x=x.values
y=y.values


In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x=LabelEncoder()
x[0:,3]=labelencoder_x.fit_transform(x[0:,3])
ct=ColumnTransformer([('one_hot_encoder', OneHotEncoder('auto'), [3])], remainder='passthrough')
x=ct.fit_transform(x)
x

array([[0.0, 1.0, 1000, 7, 2],
       [1.0, 0.0, 1030, 7, 1],
       [1.0, 0.0, 1060, 1, 1],
       [1.0, 0.0, 1090, 6, 1],
       [0.0, 1.0, 1120, 0, 2],
       [0.0, 1.0, 1150, 1, 1],
       [0.0, 1.0, 1180, 6, 2],
       [1.0, 0.0, 1210, 0, 1],
       [0.0, 1.0, 1240, 0, 2],
       [1.0, 0.0, 1270, 7, 1],
       [1.0, 0.0, 1300, 10, 2],
       [0.0, 1.0, 1330, 3, 2],
       [0.0, 1.0, 1360, 3, 3],
       [0.0, 1.0, 1390, 8, 3],
       [1.0, 0.0, 1420, 3, 2],
       [0.0, 1.0, 1450, 7, 2],
       [0.0, 1.0, 1480, 8, 3],
       [1.0, 0.0, 1510, 7, 2],
       [1.0, 0.0, 1540, 6, 3],
       [1.0, 0.0, 1570, 8, 3],
       [1.0, 0.0, 1600, 6, 2],
       [0.0, 1.0, 1630, 4, 3],
       [0.0, 1.0, 1660, 1, 3],
       [0.0, 1.0, 1690, 3, 3],
       [1.0, 0.0, 1720, 3, 3],
       [1.0, 0.0, 1750, 0, 2],
       [1.0, 0.0, 1780, 4, 2],
       [0.0, 1.0, 1810, 1, 3],
       [1.0, 0.0, 1840, 6, 2],
       [1.0, 0.0, 1870, 6, 3],
       [0.0, 1.0, 1900, 8, 2],
       [0.0, 1.0, 1930, 8, 2],
       

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [7]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()
model=linear.fit(x_train,y_train)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
prediction=model.predict(x_train)
prediction

array([[10261.09969146],
       [16783.6496692 ],
       [10688.12314932],
       [ 7874.94886478],
       [11554.59913278],
       [ 4179.44154929],
       [ 9518.66503006],
       [12942.70424656],
       [13699.00728567],
       [ 9747.6888605 ],
       [15918.12316192],
       [10959.59124831],
       [ 6603.04626674],
       [10371.47269399],
       [14655.0985638 ],
       [18959.28208329],
       [ 9659.31281761],
       [ 8844.90852063],
       [13545.64065477],
       [ 9408.49208571],
       [16814.1245124 ],
       [13478.66139697],
       [ 3364.08777613],
       [16270.23883824],
       [ 7998.79012866],
       [15969.24537222],
       [15286.61086286],
       [13824.08780133],
       [ 8777.92926283],
       [ 5898.81491411],
       [ 4921.12679269],
       [ 7675.25034318],
       [ 8528.05800711],
       [ 9277.67177427],
       [ 4039.74323792],
       [12934.77572281],
       [10591.6185245 ],
       [11238.98787105],
       [12495.0334216 ],
       [ 4136.24786274]])

In [9]:
input=[[0.0, 1.0, 1000, 7, 2]]
ans=model.predict(input)
ans

array([[6022.65617798]])

In [10]:
r=model.score(x_train,y_train)
r

0.9447721894495485